# Generated by Django 3.0.4 on 2020-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('stats_general_json', models.TextField()),
                ('stats_map_json', models.TextField()),
                ('stats_mvm_json', models.TextField()),
            ],
        ),
    ]
