# Generated by Django 3.0.4 on 2020-04-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerStats',
            new_name='PlayerStat',
        ),
    ]
