# Generated by Django 3.0.4 on 2020-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0002_auto_20200410_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('steamid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('avatar_url_medium', models.URLField()),
                ('avatar_url_full', models.URLField()),
                ('profile_url', models.URLField()),
                ('timecreated', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='playerstat',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='id',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='has_public_stats',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='steamid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
