# Generated by Django 3.0.4 on 2020-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0003_auto_20200411_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='avatar_url_small',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
