# Generated by Django 3.0.4 on 2020-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0004_playerprofile_avatar_url_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('steamid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50)),
                ('avatar_url_small', models.URLField()),
                ('avatar_url_medium', models.URLField()),
                ('avatar_url_full', models.URLField()),
                ('profile_url', models.URLField()),
                ('account_created_at', models.DateTimeField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_public_stats', models.BooleanField()),
                ('stats_general_json', models.TextField()),
                ('stats_map_json', models.TextField()),
                ('stats_mvm_json', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
        migrations.DeleteModel(
            name='PlayerStat',
        ),
    ]
