# Generated by Django 3.0.4 on 2020-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0005_auto_20200421_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='public_profile',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='account_created_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
