# Generated by Django 3.0.4 on 2020-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0006_auto_20200422_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='account_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
