# Generated by Django 3.0.4 on 2020-04-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0008_auto_20200428_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='stats_general_json',
            new_name='stats_general',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='stats_map_json',
            new_name='stats_map',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='stats_mvm_json',
            new_name='stats_mvm',
        ),
    ]
