# Generated by Django 3.0.4 on 2020-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0009_auto_20200430_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='main_class',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
