# Generated by Django 3.0.4 on 2020-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0010_player_main_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
