STEAM_API_GAMESTATS_URL = "https://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0002/?appid=440&key=%s&format=json&steamid=%s"
STEAM_API_PLAYERSUMMARY_URL ="http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=%s&steamids=%s"
STEAM_API_RESOLVEVANITYURL_URL = "https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=%s&vanityurl=%s"
STEAM_API_GETSTEAMLEVEL_URL = "https://api.steampowered.com/IPlayerService/GetSteamLevel/v1/?key=%s&steamid=%s"
STEAM_API_PLAYTIMES_URL = "https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=%s&steamid=%s&include_played_free_games=1"
