TRACKED_FIELDS = [
    "Scout.accum.iPlayTime",
    "Soldier.accum.iPlayTime",
    "Pyro.accum.iPlayTime",
    "Demoman.accum.iPlayTime",
    "Heavy.accum.iPlayTime",
    "Engineer.accum.iPlayTime",
    "Medic.accum.iPlayTime",
    "Sniper.accum.iPlayTime",
    "Spy.accum.iPlayTime",

    "Scout.accum.iNumberOfKills",
    "Soldier.accum.iNumberOfKills",
    "Pyro.accum.iNumberOfKills",
    "Demoman.accum.iNumberOfKills",
    "Heavy.accum.iNumberOfKills",
    "Engineer.accum.iNumberOfKills",
    "Medic.accum.iNumberOfKills",
    "Sniper.accum.iNumberOfKills",
    "Spy.accum.iNumberOfKills",

    "Scout.accum.iDamageDealt",
    "Soldier.accum.iDamageDealt",
    "Pyro.accum.iDamageDealt",
    "Demoman.accum.iDamageDealt",
    "Heavy.accum.iDamageDealt",
    "Engineer.accum.iDamageDealt",
    "Medic.accum.iDamageDealt",
    "Sniper.accum.iDamageDealt",
    "Spy.accum.iDamageDealt",

    "Scout.accum.iDominations",
    "Soldier.accum.iDominations",
    "Pyro.accum.iDominations",
    "Demoman.accum.iDominations",
    "Heavy.accum.iDominations",
    "Engineer.accum.iDominations",
    "Medic.accum.iDominations",
    "Sniper.accum.iDominations",
    "Spy.accum.iDominations",
    
    "Scout.mvm.accum.iPlayTime",
    "Soldier.mvm.accum.iPlayTime",
    "Pyro.mvm.accum.iPlayTime",
    "Demoman.mvm.accum.iPlayTime",
    "Heavy.mvm.accum.iPlayTime",
    "Engineer.mvm.accum.iPlayTime",
    "Medic.mvm.accum.iPlayTime",
    "Sniper.mvm.accum.iPlayTime",
    "Spy.mvm.accum.iPlayTime",

    "Medic.accum.iNumInvulnerable",
    "Spy.accum.iBackstabs",
    "Engineer.accum.iBuildingsBuilt",
    "Sniper.accum.iHeadshots",
    "Spy.accum.iHeadshots",
    "Medic.accum.iHealthPointsHealed",
]